### ISSUE TITLE
X509 Support needs ways to Extract Certificate Data

### ISSUE THREAD

**Issue by mitsuhiko** [sfackler/rust-openssl#252] opened 2015-08-07 17:51 UTC
Currently it's impossible to extract the validity dates, SANs or any other important information from the x509 object.

**Comment by dweinstein** [comment] 2016-08-17 03:01
#435 is technically a dupe of this one w/ regard to validity date, and that feature should be coming soon with #436

**Comment by sfackler** [comment] 2016-08-17 03:17
SANs are also supported at this point. I guess we can leave this open for other certificate data items, but it'd be nice to have a checklist of stuff people care about.

**Comment by sfackler** [comment] 2016-11-07 13:49
Validity dates and SANs are now accessible - please file follow up issues for anything else that needs to be exposed!

**Closed by sfackler** 2016-11-07 13:49 UTC
