### ISSUE TITLE
OPENSSL_STATIC ignored if pkg-config succeeds

### ISSUE THREAD

**Issue by harmic** [sfackler/rust-openssl#878] opened 2018-03-14 03:49 UTC
In a system with pkg-config working, if you give this:

`OPENSSL_STATIC=1 cargo build
`

then OPENSSL_STATIC is ignored. The reason is that `build.rs` calls `try_pkg_config` before it even considers OPENSSL_STATIC, and if `try_pkg_config` succeeds it exits build.rs early.

The workaround is to set both OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR manually so that `try_pkg_config` is never invoked. The documentation does not state this as a requirement though.

See also: [how-do-i-statically-link-the-openssl-sys-crate-into-a-shared-library](https://stackoverflow.com/questions/49263452/how-do-i-statically-link-the-openssl-sys-crate-into-a-shared-library)

**Comment by sfackler** [comment] 2018-03-14 04:00
pkg-config also looks at OPENSSL_STATIC, but you may be running into https://github.com/alexcrichton/pkg-config-rs/pull/37

**Comment by sfackler** [comment] 2018-03-14 04:01
Closing as a duplicate of #877

**Closed by sfackler** 2018-03-14 04:01 UTC
