### ISSUE TITLE
openssl breaks housleyjk/ws-rs in 0.7.2

### ISSUE THREAD

**Issue by alkis** [sfackler/rust-openssl#323] opened 2015-12-17 23:55 UTC
This worked in 0.7.1 but doesn't in 0.7.2.

See https://github.com/housleyjk/ws-rs/issues/17 for instructions to reproduce; more particularly [this comment](https://github.com/housleyjk/ws-rs/issues/17#issuecomment-165580563).

**Comment by sfackler** [comment] 2015-12-18 00:41
Ah, looks like the issue is that we need to treat read/write errors with the `NotConnected` kind as nonfatal like we do for `WouldBlock`. The error is happening because the SSL handshake's starting before the socket's done connecting to the remote server.

**Comment by sfackler** [comment] 2015-12-18 00:55
Just pushed the fix up. It seems to work for me locally (overriding the openssl dependency with a `.cargo/config`). If it seems to do the right thing for you as well, I'll push out a new release.

**Closed** 2015-12-18 00:54 UTC

**Comment by alkis** [comment] 2015-12-18 01:03
Confirmed working with an override in .cargo/config synced to master. Thanks for the fast fix Steven!

**Comment by sfackler** [comment] 2015-12-18 01:07
Cool, will release when I get back home in a couple hours.

**Comment by sfackler** [comment] 2015-12-18 05:31
Released v0.7.3
