### ISSUE TITLE
error while building app

### ISSUE THREAD

**Issue by Masber** [sfackler/rust-openssl#2184] opened 2024-02-22 13:23 UTC
Dear rust-openssl community,

I have a github pipeline to build the artifacts of my application, for some reason the pipeline fails when building the binaries for the apple target.

```
 error: failed to run custom build command for `openssl-sys v0.9.101`

Caused by:
  process didn't exit successfully: `/Users/runner/work/manta/manta/target/dist/build/openssl-sys-48e4210274a29364/build-script-main` (exit status: 101)
```

and

```
  --- stderr
  make: *** read jobs pipe: Resource temporarily unavailable.  Stop.
  make: *** Waiting for unfinished jobs....
  thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error building OpenSSL:
      Command: cd "/Users/runner/work/manta/manta/target/x86_64-apple-darwin/dist/build/openssl-sys-a8c5a16dc1fd68a5/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=15,20 --jobserver-auth=15,20" "make" "build_libs"
      Exit status: exit status: 2


      
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
  × failed to find bin manta (manta 1.22.16 (path+file:///Users/runner/work/manta/manta)) -- did the cargo build above
  │ have errors?
```

Full pipeline output can be seen here https://github.com/eth-cscs/manta/actions/runs/8004159748/job/21860989556#step:8:607

Any advice?

thank you very much

**Comment by Skepfyr** [comment] 2024-02-22 14:44
It looks like you've hit the same issue as #2179, which appears to be caused by an issue with the cc crate, although you might be able to workaround it by disabling the parallel feature. It might be worth raising this with cc directly (if it hasn't been done already).

**Comment by Masber** [comment] 2024-02-23 12:10
but rust-openssl is the one using cc as a dependency, I think it is also in their benefit to contact the developers of cc crate? I checked and I have the impression the cc developers are already working in a solution

**Comment by NobodyXu** [comment] 2024-02-24 03:19
cc 1.0.87 has released which shall fix this.

**Comment by Skepfyr** [comment] 2024-02-24 15:09
@Masber can you check that this has fixed the issue for you. I can't see why it wouldn't but best to check.

**Comment by ohsayan** [comment] 2024-02-24 18:16
Tuning in here because we also had [one of our builds crash as well](https://github.com/skytable/skytable/actions/runs/8032312860/job/21941583130)

**Comment by NobodyXu** [comment] 2024-02-24 22:22
@ohsayan Did it work before bumping openssl-src, while using cc 1.0.87?

**Comment by NobodyXu** [comment] 2024-02-24 23:34
@ohsayan can you try rust-lang/cc-rs#973 to see if it fixes your issue?

**Comment by ohsayan** [comment] 2024-02-25 05:47
@NobodyXu Reverted dependency updates to openssl-* and cc as well. [Builds are passing](https://github.com/skytable/skytable/actions/runs/8035844942/job/21948881092#step:7) with [this change](https://github.com/skytable/skytable/commit/f4a18234628f54e2b9f94e4e6906298f24ef15fe).

**Comment by NobodyXu** [comment] 2024-02-25 06:09
@ohsayan Can you please try rust-lang/cc-rs#973 to see if it fixes your issue?

**Comment by NobodyXu** [comment] 2024-02-25 06:34
I got absolutely no idea why it fails.

I checked the openssl-src, it doesn't call Build::compile anywhere so cc won't even try to build jobserver, let alone setting `O_NONBLOCK` on it.

**Comment by ohsayan** [comment] 2024-02-25 06:54
Tested separately. As soon as I bump OpenSSL, the build fails (see [this workflow run](https://github.com/skytable/skytable/actions/runs/8036179020/job/21949574451)).

The only change that was made:
```diff
- openssl = { version = "0.10.63", features = ["vendored"] }
+ openssl = { version = "0.10.64", features = ["vendored"] }
```
and after a `cargo update`, `cc` was updated in the lockfile:

```diff
[[package]]
name = "cc"
- version = "1.0.83"
+ version = "1.0.87"
```

**Comment by NobodyXu** [comment] 2024-02-25 06:57
Can you test rust-lang/cc#975 please?

It should finally fix the bug.

**Comment by ohsayan** [comment] 2024-02-25 07:09
@NobodyXu unfortunately, the build still fails. I attempted to use the commit revision directly (rust-lang/cc-rs@46eedd0) but the [build still failed](https://github.com/skytable/skytable/actions/runs/8036261317/job/21949756282).

**Comment by NobodyXu** [comment] 2024-02-25 07:13
@ohsayan I'm not sure if specify a git dependency  in your project works, I think you might need to use patch.crates-io instead.

checking your Cargo.lock, you got two cc, one is 1.0.87, another is git version of it.

**Comment by ohsayan** [comment] 2024-02-25 07:16
@NobodyXu my bad, I'll use an override (patch) and see. I'll get back to you in a moment.

**Comment by ohsayan** [comment] 2024-02-25 07:24
@NobodyXu confirming that this change indeed fixes the build

**Comment by NobodyXu** [comment] 2024-02-25 15:16
cc 1.0.88 has released!

**Comment by frol** [comment] 2024-02-26 16:40
Users of my CLI have just also reported and I confirmed that I still see this error even though I have cc v1.0.88 (only one) and openssl-sys v0.9.101. Here is the command to reproduce:

```
cargo install cargo-near
```

**Comment by brynary** [comment] 2024-02-26 16:57
This error is still occurring for mv on `cc` v1.0.88 as well

**Comment by leighmcculloch** [comment] 2024-04-23 04:56
This error still occurred for me on `cc` `v1.0.87`, and `v1.0.88`. Upgrading to `v1.0.95` resolved it though.

**Comment by Skepfyr** [comment] 2024-05-07 16:41
The last few comments suggest to me this is resolved, I'm on a little bit of a spring clean so I'm going to say thank you to @NobodyXu and close this. If this isn't resolved for some reason feel free to re-open/comment.

**Closed by Skepfyr** 2024-05-07 16:41 UTC
