### ISSUE TITLE
Compile repeatedly

### ISSUE THREAD

**Issue by jsamtsang** [sfackler/rust-openssl#2180] opened 2024-02-21 13:19 UTC
![11](https://github.com/sfackler/rust-openssl/assets/31495837/56e9214e-502d-42a8-a553-5abe3fccd71d)

openssl v0.10.64
openssl-sys v0.9.100
rust v1.76.0

This version will be recompiled every time it is run, which takes a lot of time and is too torturous.
Even if there are no changes, the compilation will be repeated.
run.stop.run....no changes！Such a simple and repeated operation has to be compiled every time, crazy！
But this won’t happen when using openssl v0.10.63、openssl-sys v0.9.99.
why?

**Comment by alex** [comment] 2024-02-21 13:21
Duplicate of https://github.com/sfackler/rust-openssl/issues/2176 -- this will be fixed with the next release (which I plan to do this evening)

**Closed by alex** 2024-02-21 13:21 UTC
